version: "3"

services:
  server:
    image: my-docker:2.1
    build: .
    volumes:
      - ./nginx:/etc/nginx
    container_name: server

  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx2:/etc/nginx
    depends_on:
      - server